### ISSUE TITLE
Python 2.7 support

### ISSUE THREAD

**Issue by PawelTroka** [dazfuller/PyUnitTestTask#2]
Does it work out of the box or is it to be implemented?

**Comment by dazfuller** [comment]
If you're running on Windows with a newer version of 2.7 then it may work.  Currently the task checks to see if it is running on a windows host or linux, if windows then it will make calls using "python" rather than "python3".  It uses the "venv" module which was backported from 3.x into 2.7.

In future the solution will be extended to use alternative virtual environment solutions so that it can cater for solutions such as virtualenv or Anaconda.

**Comment by dazfuller** [comment]
Closing as no follow up questions, hopefully the original answer was sufficient
